@HotelListingAPI_HostAddress = https://localhost:7262
@json = application/json

GET {{HotelListingAPI_HostAddress}}/api/country

###

POST {{HotelListingAPI_HostAddress}}/api/country
Content-Type: application/json

{
  "name":"Austria",
  "shortName":"AUT"
}

###

DELETE {{HotelListingAPI_HostAddress}}/api/country/{{id}}

###

GET {{HotelListingAPI_HostAddress}}/api/country/{{id}}

###

PUT {{HotelListingAPI_HostAddress}}/api/country/{{id}}
Content-Type: application/json

{
  //UpdateCountryDto
}

###

GET {{HotelListingAPI_HostAddress}}/api/hotel
Authorization:Basic dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzd29yZDE=

###

POST {{HotelListingAPI_HostAddress}}/api/hotel
Content-Type: application/json

{
  "Name": "New Hotel Beach",
  "Address": "Beach Street 11",
  "Rating": 3.3,
  "CountryId":2
}

###

DELETE {{HotelListingAPI_HostAddress}}/api/hotel/{{id}}

###
GET {{HotelListingAPI_HostAddress}}/api/hotel/{{id}}

###
PUT {{HotelListingAPI_HostAddress}}/api/hotel/{{id}}
Content-Type: application/json
{
  "Id":4,
  "Name": "New Hotel Beach 2",
  "Address": "Beach Street 11",
  "Rating": 3.3,
  "CountryId":2
}

###

POST {{HotelListingAPI_HostAddress}}/api/auth/register
Content-Type: {{json}}
{
    "email":"user1@localhost.com",
    "password":"P@ssword1",
    "firstName":"First",
    "lastName":"Last"
}

###

POST {{HotelListingAPI_HostAddress}}/api/auth/login
Content-Type: {{json}}
{
    "email":"user1@localhost.com",
    "password":"P@ssword1"
}
